# Generated by Django 5.2.6 on 2025-09-08 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_match_options_alter_match_team_a_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ('-start_date', 'id')},
        ),
        migrations.AddField(
            model_name='tournament',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='managed_tournaments', to=settings.AUTH_USER_MODEL),
        ),
    ]
