# Generated by Django 5.2.6 on 2025-09-27 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('tournaments', '0004_alter_tournament_options_tournament_admins'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(choices=[('de_mirage', 'Mirage'), ('de_dust2', 'Dust2'), ('de_ancient', 'Ancient'), ('de_train', 'Train'), ('de_nuke', 'Nuke'), ('de_inferno', 'Inferno'), ('de_overpass', 'Overpass')], max_length=50)),
                ('order', models.PositiveIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_bans', to='tournaments.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
