# Generated by Django 5.2.6 on 2025-10-19 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teaminvite'),
        ('tournaments', '0005_mapban'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapban',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='mapban',
            name='action',
            field=models.CharField(choices=[('ban', 'Ban'), ('pick', 'Pick')], default='ban', max_length=8),
        ),
        migrations.AddField(
            model_name='mapban',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='final_map_code',
            field=models.CharField(blank=True, choices=[('de_mirage', 'Mirage'), ('de_dust2', 'Dust2'), ('de_ancient', 'Ancient'), ('de_train', 'Train'), ('de_nuke', 'Nuke'), ('de_inferno', 'Inferno'), ('de_overpass', 'Overpass')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='server_addr',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='match',
            name='veto_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='veto_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='veto_state',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('done', 'Done')], default='idle', max_length=8),
        ),
        migrations.AddField(
            model_name='match',
            name='veto_timeout',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='match',
            name='veto_turn',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1),
        ),
        migrations.AddIndex(
            model_name='mapban',
            index=models.Index(fields=['match', 'order'], name='tournaments_match_i_08e3f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='mapban',
            constraint=models.UniqueConstraint(fields=('match', 'map_name'), name='unique_map_once_per_match'),
        ),
    ]
