# Generated by Django 5.2.6 on 2025-10-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_alter_mapban_options_mapban_action_mapban_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/logos/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/posters/'),
        ),
    ]
