# Generated by Django 5.2.6 on 2025-11-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_tournament_logo_tournament_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('running', 'Running'), ('finished', 'Finished')], default='scheduled', max_length=16),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('running', 'Running'), ('finished', 'Finished')], default='upcoming', max_length=16),
        ),
    ]
