# Generated by Django 5.2.6 on 2025-10-07 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faceit_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stats_source',
            field=models.CharField(choices=[('cs2', 'CS2 Premier/MM'), ('faceit', 'Faceit')], default='cs2', max_length=20),
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('cs2', 'CS2'), ('faceit', 'Faceit')], max_length=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('matches', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('kd_ratio', models.FloatField(default=0.0)),
                ('hs_percent', models.FloatField(default=0.0)),
                ('winrate', models.FloatField(default=0.0)),
                ('faceit_level', models.IntegerField(blank=True, null=True)),
                ('elo', models.IntegerField(blank=True, null=True)),
                ('premier_rating', models.IntegerField(blank=True, null=True)),
                ('total_kills', models.IntegerField(default=0)),
                ('total_deaths', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
