# Generated by Django 5.2.6 on 2025-10-08 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_faceit_id_user_stats_source_playerstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stats_source',
        ),
        migrations.DeleteModel(
            name='PlayerStats',
        ),
    ]
