# Generated by Django 5.2.6 on 2025-09-05 16:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Введите IPv4, например 192.168.1.10', regex='^(\\d{1,3}\\.){3}\\d{1,3}$')])),
                ('game_port', models.PositiveIntegerField(default=27015, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('query_port', models.PositiveIntegerField(default=27015, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('location', models.CharField(blank=True, max_length=64)),
                ('note', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_allocated', models.BooleanField(default=False)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('ip', 'game_port')},
            },
        ),
    ]
